spring.application.name=backend

jwt.secret=iv7vNc5XMsatc0sOznjkxnFAXp9KTZhzZfc3YTtC3rR

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/task_manager
spring.datasource.username=postgres
spring.datasource.password=123

# Mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=nikum395@gmail.com
spring.mail.password=xdvzfjcewvphxacx
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# JPA
spring.jpa.hibernate.ddl-auto=validate

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
