spring.application.name=backend

jwt.secret=${JWT_SECRET:iv7vNc5XMsatc0sOznjkxnFAXp9KTZhzZfc3YTtC3rR}

# Database
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/task_manager}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:123}

# Mail
spring.mail.host=${SPRING_MAIL_HOST:smtp.gmail.com}
spring.mail.port=${SPRING_MAIL_PORT:587}
spring.mail.username=${SPRING_MAIL_USERNAME:nikum395@gmail.com}
spring.mail.password=${SPRING_MAIL_PASSWORD:xdvzfjcewvphxacx}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# Task notifications
notifications.task-due-window-days=1
notifications.task-due-check-delay-ms=3600000
